"""Add guest_email to bookings

Revision ID: 4c072e1cf1ed
Revises: 8157f3b40a61
Create Date: 2025-12-04 11:56:18.095681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c072e1cf1ed'
down_revision: Union[str, Sequence[str], None] = '8157f3b40a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_email', sa.String(), nullable=True))
    op.alter_column('bookings', 'tickets_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'tickets_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'guest_email')
    # ### end Alembic commands ###
