"""Add tickets_count and guest_name to bookings

Revision ID: 8157f3b40a61
Revises: 42ac69ea174a
Create Date: 2025-12-04 11:35:01.484473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8157f3b40a61'
down_revision: Union[str, Sequence[str], None] = '42ac69ea174a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tickets_count', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('guest_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guest_name')
    op.drop_column('bookings', 'tickets_count')
    # ### end Alembic commands ###
